// apps/multi-react/src/components/ChatPanel.tsx
import { useState, useRef, useEffect } from 'react';
import type { MessageItem } from '../hooks/useAgent';

interface ChatPanelProps {
  messages: MessageItem[];
  sending: boolean;
  onSend: (text: string) => void;
}

export function ChatPanel({ messages, sending, onSend }: ChatPanelProps) {
  const [input, setInput] = useState('');
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      if (input.trim() && !sending) {
        onSend(input.trim());
        setInput('');
      }
    }
  }

  return (
    <div className="chat-panel">
      <div className="chat-messages">
        {messages.map((m) => (
          <div key={m.id} className={`chat-bubble chat-bubble--${m.role}`}>
            <span className="chat-role">{m.role}</span>
            <span className="chat-text">{m.content}</span>
          </div>
        ))}
        <div ref={bottomRef} />
      </div>
      <div className="chat-input-bar">
        <input
          type="text"
          className="chat-input"
          placeholder={sending ? 'Generating...' : 'Ask for a widget...'}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          disabled={sending}
        />
        <button
          className="btn btn-accent"
          disabled={sending || !input.trim()}
          onClick={() => {
            if (input.trim()) {
              onSend(input.trim());
              setInput('');
            }
          }}
        >
          {sending ? 'Stop' : 'Send'}
        </button>
      </div>
    </div>
  );
}

// apps/multi-vue/src/components/ChatPanel.vue
<script setup lang="ts">
import { ref, nextTick, watch } from 'vue';

const props = defineProps<{
  messages: { id: string; role: 'user' | 'assistant' | 'system'; text: string }[];
  generating: boolean;
}>();

const emit = defineEmits<{
  send: [msg: string];
  stop: [];
}>();

const input = ref('');
const scrollEl = ref<HTMLElement>();

function onSend() {
  if (!input.value.trim()) return;
  emit('send', input.value.trim());
  input.value = '';
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault();
    onSend();
  }
}

// Auto-scroll on new messages
watch(
  () => props.messages.length,
  async () => {
    await nextTick();
    if (scrollEl.value) {
      scrollEl.value.scrollTop = scrollEl.value.scrollHeight;
    }
  },
);
</script>

<template>
  <div style="display: flex; flex-direction: column; flex: 1; overflow: hidden">
    <div ref="scrollEl" class="chat-messages">
      <div
        v-for="msg in messages"
        :key="msg.id"
        class="chat-msg"
        :class="msg.role"
      >
        {{ msg.text }}
      </div>
      <div v-if="!messages.length" class="empty-state" style="flex: 1">
        Type a message to start generating widgets.
      </div>
    </div>

    <div class="chat-input-row">
      <input
        v-model="input"
        type="text"
        :placeholder="generating ? 'Generating...' : 'Ask for a widget...'"
        :disabled="generating"
        @keydown="onKeydown"
      />
      <button
        v-if="generating"
        class="btn btn-danger btn-sm"
        @click="emit('stop')"
      >
        Stop
      </button>
      <button
        v-else
        class="btn btn-accent btn-sm"
        :disabled="!input.trim()"
        @click="onSend"
      >
        Send
      </button>
    </div>
  </div>
</template>
