// apps/multi-vue/src/App.vue
<script setup lang="ts">
import { useServers } from './composables/useServers';
import { useAgent } from './composables/useAgent';
import ServerSelector from './components/ServerSelector.vue';
import McpConnector from './components/McpConnector.vue';
import ChatPanel from './components/ChatPanel.vue';
import WidgetGrid from './components/WidgetGrid.vue';

const { serverOptions, activeServers, layers, toggle, enableAll, disableAll } = useServers();
const {
  messages, widgets, generating, elapsed, toolCount, lastTool, llm,
  connectedMcpUrls,
  send, stop, connectMcp, disconnectMcp, clearWidgets,
} = useAgent();

const LLM_OPTIONS: { value: string; label: string }[] = [
  { value: 'haiku', label: 'Haiku' },
  { value: 'sonnet', label: 'Sonnet' },
  { value: 'opus', label: 'Opus' },
];

function onSend(msg: string) {
  send(msg, layers.value);
}

function onRemoveWidget(id: string) {
  widgets.value = widgets.value.filter(w => w.id !== id);
}
</script>

<template>
  <div class="app-shell">
    <!-- Topbar -->
    <header class="topbar">
      <span class="topbar-title">Auto-UI <span>multi-vue</span></span>
      <div class="topbar-spacer" />

      <!-- LLM selector -->
      <select v-model="llm" style="width: auto; max-width: 140px">
        <option v-for="opt in LLM_OPTIONS" :key="opt.value" :value="opt.value">
          {{ opt.label }}
        </option>
      </select>

      <!-- Agent progress -->
      <template v-if="generating">
        <div class="progress-bar" style="border: none; padding: 0; gap: 6px">
          <div class="spinner" />
          <span>{{ elapsed }}s</span>
          <span v-if="toolCount">&middot; {{ toolCount }} tools</span>
          <span v-if="lastTool">&middot; {{ lastTool }}</span>
        </div>
      </template>
    </header>

    <!-- Sidebar -->
    <aside class="sidebar">
      <div class="sidebar-scroll">
        <ServerSelector
          :servers="serverOptions"
          @toggle="toggle"
          @enable-all="enableAll"
          @disable-all="disableAll"
        />

        <McpConnector
          :connected-urls="connectedMcpUrls"
          @connect="connectMcp"
          @disconnect="disconnectMcp"
        />
      </div>

      <ChatPanel
        :messages="messages"
        :generating="generating"
        @send="onSend"
        @stop="stop"
      />
    </aside>

    <!-- Main widget area -->
    <main class="main-area">
      <WidgetGrid
        :widgets="widgets"
        :servers="activeServers"
        @remove="onRemoveWidget"
        @clear="clearWidgets"
      />
    </main>
  </div>
</template>

// apps/multi-react/src/App.tsx
import { useState, useCallback } from 'react';
import { ChatPanel } from './components/ChatPanel';
import { WidgetGrid } from './components/WidgetGrid';
import { ServerSelector } from './components/ServerSelector';
import { McpConnector } from './components/McpConnector';
import { useAgent } from './hooks/useAgent';
import { useServers } from './hooks/useServers';
import type { WebMcpServer } from '@webmcp-auto-ui/core';
import type { RemoteModelId } from '@webmcp-auto-ui/agent';

const LLM_OPTIONS: { id: RemoteModelId; label: string }[] = [
  { id: 'haiku', label: 'Haiku' },
  { id: 'sonnet', label: 'Sonnet' },
  { id: 'opus', label: 'Opus' },
];

export default function App() {
  const [model, setModel] = useState<RemoteModelId>('haiku');
  const { enabledServers, toggleServer, serverOptions } = useServers();

  const activeServers: WebMcpServer[] = enabledServers;

  const {
    messages,
    widgets,
    sending,
    sendMessage,
    clearWidgets,
    mcpUrl,
    setMcpUrl,
    mcpConnected,
    mcpName,
    mcpConnecting,
    connectMcp,
    disconnectMcp,
  } = useAgent({ servers: activeServers, model });

  const handleSend = useCallback(
    (text: string) => sendMessage(text),
    [sendMessage],
  );

  return (
    <div className="app-shell">
      {/* ── Sidebar ── */}
      <aside className="sidebar">
        <h1 className="sidebar-title">
          Auto-UI <span className="accent">multi-react</span>
        </h1>

        {/* LLM selector */}
        <section className="sidebar-section">
          <label className="section-label">LLM</label>
          <select
            className="select"
            value={model}
            onChange={(e) => setModel(e.target.value as RemoteModelId)}
          >
            {LLM_OPTIONS.map((o) => (
              <option key={o.id} value={o.id}>
                {o.label}
              </option>
            ))}
          </select>
        </section>

        {/* Server packs */}
        <section className="sidebar-section">
          <label className="section-label">Widget Packs</label>
          <ServerSelector options={serverOptions} onToggle={toggleServer} />
        </section>

        {/* MCP connector */}
        <section className="sidebar-section">
          <label className="section-label">MCP Server</label>
          <McpConnector
            url={mcpUrl}
            onUrlChange={setMcpUrl}
            connected={mcpConnected}
            connecting={mcpConnecting}
            serverName={mcpName}
            onConnect={connectMcp}
            onDisconnect={disconnectMcp}
          />
        </section>

        {widgets.length > 0 && (
          <button className="btn btn-ghost" onClick={clearWidgets}>
            Clear widgets
          </button>
        )}
      </aside>

      {/* ── Main area ── */}
      <main className="main-area">
        <WidgetGrid widgets={widgets} servers={activeServers} />
        <ChatPanel
          messages={messages}
          sending={sending}
          onSend={handleSend}
        />
      </main>
    </div>
  );
}
