// apps/multi-vue/src/components/McpConnector.vue
<script setup lang="ts">
import { ref } from 'vue';
import { MCP_DEMO_SERVERS } from '@webmcp-auto-ui/sdk';

defineProps<{
  connectedUrls: string[];
}>();

const emit = defineEmits<{
  connect: [url: string];
  disconnect: [url: string];
}>();

const url = ref('');

function onConnect() {
  if (!url.value.trim()) return;
  emit('connect', url.value.trim());
  url.value = '';
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter') onConnect();
}

function connectDemo(demoUrl: string) {
  emit('connect', demoUrl);
}
</script>

<template>
  <div class="section">
    <div class="section-title">MCP Servers</div>

    <div style="display: flex; gap: 6px">
      <input
        v-model="url"
        type="url"
        placeholder="wss:// or https://"
        @keydown="onKeydown"
      />
      <button class="btn btn-sm btn-accent" @click="onConnect">+</button>
    </div>

    <!-- Connected servers -->
    <div v-if="connectedUrls.length" style="display: flex; flex-wrap: wrap; gap: 4px; margin-top: 4px">
      <span
        v-for="u in connectedUrls"
        :key="u"
        class="server-tag"
      >
        <span class="status-dot connected" />
        {{ u.replace(/https?:\/\//, '').split('/')[0] }}
        <span class="close" @click="emit('disconnect', u)">&times;</span>
      </span>
    </div>

    <!-- Demo servers -->
    <div class="section-title" style="margin-top: 8px">Demo Servers</div>
    <div style="display: flex; flex-direction: column; gap: 4px">
      <button
        v-for="demo in MCP_DEMO_SERVERS"
        :key="demo.id"
        class="btn btn-sm"
        :disabled="connectedUrls.includes(demo.url)"
        @click="connectDemo(demo.url)"
      >
        {{ demo.name }}
      </button>
    </div>
  </div>
</template>

// apps/multi-react/src/components/McpConnector.tsx
interface McpConnectorProps {
  url: string;
  onUrlChange: (url: string) => void;
  connected: boolean;
  connecting: boolean;
  serverName: string;
  onConnect: () => void;
  onDisconnect: () => void;
}

export function McpConnector({
  url,
  onUrlChange,
  connected,
  connecting,
  serverName,
  onConnect,
  onDisconnect,
}: McpConnectorProps) {
  if (connected) {
    return (
      <div className="mcp-connected">
        <span className="mcp-dot mcp-dot--on" />
        <span className="mcp-name">{serverName}</span>
        <button className="btn btn-ghost btn-sm" onClick={onDisconnect}>
          Disconnect
        </button>
      </div>
    );
  }

  return (
    <div className="mcp-connector">
      <input
        type="text"
        className="mcp-input"
        placeholder="https://mcp-server.example/sse"
        value={url}
        onChange={(e) => onUrlChange(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === 'Enter') onConnect();
        }}
        disabled={connecting}
      />
      <button
        className="btn btn-accent btn-sm"
        onClick={onConnect}
        disabled={connecting || !url.trim()}
      >
        {connecting ? '...' : 'Connect'}
      </button>
    </div>
  );
}
